language: csharp
solution: XmTemplating.sln
install:
  - sudo apt-get install nunit-console
  - nuget restore XmTemplating.sln
script:
  - xbuild /p:Configuration=Release XmTemplating.sln
  - nunit-console Com.Ericmas001.XmTemplating.Tests/bin/Release/Com.Ericmas001.XmTemplating.Tests.dll
