language: csharp
solution: XmTemplating.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore XmTemplating.sln
after_script:
  - nunit-console Com.Ericmas001.XmTemplating.Tests/bin/Release/Com.Ericmas001.XmTemplating.Tests.dll
