language: csharp
solution: XmTemplating.sln
install:
  - nuget restore XmTemplating.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
  script:
  - xbuild /p:Configuration=Release XmTemplating.sln
  - mono ./testrunner/NUnit.Runners.3.5.0/tools/nunit-console.exe ./Com.Ericmas001.XmTemplating.Tests/bin/Release/Com.Ericmas001.XmTemplating.Tests.dll